//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.21 at 12:50:17 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kaziulin.by/InternetShop/ws/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.kaziulin.InternetShop.ws.products;
